### ISSUE TITLE
Converting KECCACK to SHA3 FIPS202

### ISSUE THREAD

**Issue by arvindrao7589** [JavaCardSpot-dev/JCSWAlgs#10]

**Comment by rams76** [comment]
The Keccak implementation obtained from the reference ( https://github.com/albertocarp/Primitives_SmartCard ) is lightweight implementation ( R+C = 200, 400 and 800) as against the standard implementation of (R+C = 1600). The implementation is modified for the number of round as per standard implementation and the results were compared. This was not complying to the requirement. The code was further modified for standard implementation of R+C=1600. The core design did not support even after adjusting the buffer sizes and error 6F00 was reported. The standard implementation in python for Compact Keccak is obtained form the keccak team web page, ref: https://github.com/gvanas/KeccakCodePackage/tree/master/Standalone/CompactFIPS202/Python
and obtained the hash for the test vectors (aa) equivalent to hex (0x61 0x61). The test vector generation is verified by comparing the hash agains the Test vectors provided at the web site:
https://github.com/gvanas/KeccakCodePackage/tree/master/tests/TestVectors . The implementation is unique and the test vector could not be verified.
