### ISSUE TITLE
Report Format

### ISSUE THREAD

**Issue by arvindrao7589** [JavaCardSpot-dev/JCSWAlgs#6]
For each Primitive

-Functions Exposed by the class
-APDU commands for different functions
-Key sizes used(if any)

For example
Zorro:
//create and init
ZorroCipher m_instance_zorro = ZorroCipher.getInstance();

//Encrypt
m_instance_zorro.process(0x21, buf, start_offset, size_of_data) returns length of cipher;
//decrypt

APDUs
Encrypt:
Decrypt: 
 
blocksize=128bit

**Comment by UCO476370** [comment]
We each primitives we need to see the possibility of Random Oracle attacks and see the weak cryptographic primitives used .
