### ISSUE TITLE
Fix redundant cast to short warning

### ISSUE THREAD

**Issue by petrs** [JavaCardSpot-dev/JCSWAlgs#7]
warning: [cast] redundant cast to short
[ant:compile] 					state[(short)((short)(y + (3*(KECCAK_VALUE_W/16)) + x))].value = (short) (sB[(short)(y + (3*(KECCAK_VALUE_W/16)) + x)].value ^ ((~ sB[(short)(y + (4*(KECCAK_VALUE_W/16)) + x)].value) & sB[(short)(y + x)].value));
[ant:compile] 					      ^

**Comment by arvindrao7589** [comment]
The warning has been resolved.
